version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "9000:9000"  # Puerto host
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"  # Mapea el puerto 27017 del contenedor al puerto 27017 del host
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
